[tool.poetry]
name = "gpt-k"
version = "0.1.0"
description = ""
authors = ["William Eliot <admin@williameliot.com>"]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^1.10.1"
black = "^21.12b0"
numpy = "^1.22.0"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
